kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ephemeral-practice
nodes:
- role: control-plane
  image: kindest/node:v1.29.1
  kubeadmConfigPatches:
  - |
    kind: KubeletConfiguration
    evictionHard:
      nodefs.available: "1Gi"
