apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptydir-example1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emptydir-example1
  template:
    metadata:
      labels:
        app: emptydir-example1
    spec:
      nodeSelector:
        env: test
      containers:
      - name: emptydir-example1
        image: busybox
        command: ["sleep", "infinity"]
        resources:
          limits:
            cpu: "50m"
            memory: "64Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
        volumeMounts:
        - mountPath: /data
          name: temp-storage
      volumes:
      - name: temp-storage
        emptyDir: {}
