apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: busybox
  template:
    nodeSelector:
      env: test
    metadata:
      labels:
        app: busybox
    spec:
      nodeSelector:
        env: test
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "infinity"]
        resources:
          limits:
            cpu: "50m"
            memory: "64Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
